name: Unit tests
on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tests with Pytest
      run: |
        pip install pytest
        pytest
        