name: Slow unit tests
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  unittest_slow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Tests with Pytest
      run: |
        pip install pytest
        export PYTHONPATH=$PYTHONPATH:.
        pytest -c ci/pytest.ini --doctest-modules -m "slow" --durations=10
