name: Unit tests
on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Tests with Pytest
      run: |
        pip install pytest
        export PYTHONPATH=$PYTHONPATH:.
        pytest -c ci/pytest.ini --doctest-modules -m "not slow" --durations=10

  unittest_in_docker_container:
    runs-on: ubuntu-latest
    container:
      image: fredrikandersson/debian-stable-python-image:stable-2019-12-24
    
    steps:
    - uses: actions/checkout@v2
    - name: Tests in Docker container
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest -c ci/pytest.ini --doctest-modules -m "not slow" --durations=10
      
